const deck = [
  // Hearts
  { title: '2 of Hearts', value: 2, type: 'Hearts' },
  { title: '3 of Hearts', value: 3, type: 'Hearts' },
  { title: '4 of Hearts', value: 4, type: 'Hearts' },
  { title: '5 of Hearts', value: 5, type: 'Hearts' },
  { title: '6 of Hearts', value: 6, type: 'Hearts' },
  { title: '7 of Hearts', value: 7, type: 'Hearts' },
  { title: '8 of Hearts', value: 8, type: 'Hearts' },
  { title: '9 of Hearts', value: 9, type: 'Hearts' },
  { title: '10 of Hearts', value: 10, type: 'Hearts' },
  { title: 'Jack of Hearts', value: 'Jack', type: 'Hearts' },
  { title: 'Queen of Hearts', value: 'Queen', type: 'Hearts' },
  { title: 'King of Hearts', value: 'King', type: 'Hearts' },
  { title: 'Ace of Hearts', value: 'Ace', type: 'Hearts' },

  // Diamonds
  { title: '2 of Diamonds', value: 2, type: 'Diamonds' },
  { title: '3 of Diamonds', value: 3, type: 'Diamonds' },
  { title: '4 of Diamonds', value: 4, type: 'Diamonds' },
  { title: '5 of Diamonds', value: 5, type: 'Diamonds' },
  { title: '6 of Diamonds', value: 6, type: 'Diamonds' },
  { title: '7 of Diamonds', value: 7, type: 'Diamonds' },
  { title: '8 of Diamonds', value: 8, type: 'Diamonds' },
  { title: '9 of Diamonds', value: 9, type: 'Diamonds' },
  { title: '10 of Diamonds', value: 10, type: 'Diamonds' },
  { title: 'Jack of Diamonds', value: 'Jack', type: 'Diamonds' },
  { title: 'Queen of Diamonds', value: 'Queen', type: 'Diamonds' },
  { title: 'King of Diamonds', value: 'King', type: 'Diamonds' },
  { title: 'Ace of Diamonds', value: 'Ace', type: 'Diamonds' },

  // Clubs
  { title: '2 of Clubs', value: 2, type: 'Clubs' },
  { title: '3 of Clubs', value: 3, type: 'Clubs' },
  { title: '4 of Clubs', value: 4, type: 'Clubs' },
  { title: '5 of Clubs', value: 5, type: 'Clubs' },
  { title: '6 of Clubs', value: 6, type: 'Clubs' },
  { title: '7 of Clubs', value: 7, type: 'Clubs' },
  { title: '8 of Clubs', value: 8, type: 'Clubs' },
  { title: '9 of Clubs', value: 9, type: 'Clubs' },
  { title: '10 of Clubs', value: 10, type: 'Clubs' },
  { title: 'Jack of Clubs', value: 'Jack', type: 'Clubs' },
  { title: 'Queen of Clubs', value: 'Queen', type: 'Clubs' },
  { title: 'King of Clubs', value: 'King', type: 'Clubs' },
  { title: 'Ace of Clubs', value: 'Ace', type: 'Clubs' },

  // Spades
  { title: '2 of Spades', value: 2, type: 'Spades' },
  { title: '3 of Spades', value: 3, type: 'Spades' },
  { title: '4 of Spades', value: 4, type: 'Spades' },
  { title: '5 of Spades', value: 5, type: 'Spades' },
  { title: '6 of Spades', value: 6, type: 'Spades' },
  { title: '7 of Spades', value: 7, type: 'Spades' },
  { title: '8 of Spades', value: 8, type: 'Spades' },
  { title: '9 of Spades', value: 9, type: 'Spades' },
  { title: '10 of Spades', value: 10, type: 'Spades' },
  { title: 'Jack of Spades', value: 'Jack', type: 'Spades' },
  { title: 'Queen of Spades', value: 'Queen', type: 'Spades' },
  { title: 'King of Spades', value: 'King', type: 'Spades' },
  { title: 'Ace of Spades', value: 'Ace', type: 'Spades' },
]

export { deck }
